### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by PoiDaisuki** [TiomTang/Empyrion-Chinese-Translation#1]
RE2的Dialogues.csv, Line 5385
dialogue_GaGCqme 写成了主线剧情里的箱子名称（应该是工程师）

另外，旧存档需要在控制台里手动用pda readdata刷新pda数据（但是可能会造成任务进度丢失）应该是出于对游戏版本更新的兼容？游戏会直接把pda数据保存在存档文件里

**Comment by TiomTang** [comment]
已更正，顺便又改了一波没改到的
