### ISSUE TITLE
服务器端PAD无法显示汉化

### ISSUE THREAD

**Issue by Daniel022059** [TiomTang/Empyrion-Chinese-Translation#2]
本地单人游戏发现PAD已经汉化了，但是通过steamcmd新建一个服务器连入后发现PAD还是英文，尝试用汉化补丁覆盖了服务器端的content文件夹，并删除了所有save重新创建playfield还是无法汉化PAD。尝试pad refresh指令，依然无效。

**Comment by TiomTang** [comment]
我测试是可以正常使用，你可能需要参考一下开服务端的教程[https://empyrion.fandom.com/wiki/Guide/Setting_Up_Dedicated_Server](url)

打汉化补丁的方法：
本体：
例如服务端路径为：C:\steamCMD\empyriondedicatedserver
你需要在本体汉化目录里面找到Content文件夹，将其复制到上面服务端路径里，覆盖原本的Content目录。

RE2：
如果你是使用RE2，首先你要把RE2的整个东西放到C:\steamCMD\empyriondedicatedserver\Content\Scenarios里面，例如：C:\steamCMD\empyriondedicatedserver\Content\Scenarios\Project Eden2
然后你要在这个目录里面打上RE2汉化包的文件覆盖，也是找到RE2汉化包里面的Content文件夹覆盖到上面这个目录里面。
在开服务器时，你还要编辑dedicated.yaml文件，将CustomScenario节点内容改为“CustomScenario: Project Eden2”，其中Project Eden2是C:\steamCMD\empyriondedicatedserver\Content\Scenarios目录里面放的RE2剧本文件夹名称。

以上应该比较详细了，不明白的话可以继续提问。

**Comment by Daniel022059** [comment]
> 我测试是可以正常使用，你可能需要参考一下开服务端的教程[https://empyrion.fandom.com/wiki/Guide/Setting_Up_Dedicated_Server](url)
> 
> 打汉化补丁的方法： 本体： 例如服务端路径为：C:\steamCMD\empyriondedicatedserver 你需要在本体汉化目录里面找到Content文件夹，将其复制到上面服务端路径里，覆盖原本的Content目录。
> 
> RE2： 如果你是使用RE2，首先你要把RE2的整个东西放到C:\steamCMD\empyriondedicatedserver\Content\Scenarios里面，例如：C:\steamCMD\empyriondedicatedserver\Content\Scenarios\Project Eden2 然后你要在这个目录里面打上RE2汉化包的文件覆盖，也是找到RE2汉化包里面的Content文件夹覆盖到上面这个目录里面。 在开服务器时，你还要编辑dedicated.yaml文件，将CustomScenario节点内容改为“CustomScenario: Project Eden2”，其中Project Eden2是C:\steamCMD\empyriondedicatedserver\Content\Scenarios目录里面放的RE2剧本文件夹名称。
> 
> 以上应该比较详细了，不明白的话可以继续提问。

问题初步找到了，服务器会默认开启Default Multiplayer这个Scenarios，由于这个Default Multiplayer没有汉化所以就不显示中文了

**Comment by TiomTang** [comment]
把本体汉化的Content打进去就行

**Comment by Daniel022059** [comment]
> 把本体汉化的Content打进去就行

感谢回复，目前暂时解决了，方法是把本体汉化的Content打进去后， 修改CustomScenario为Default Random。
