### ISSUE TITLE
颜色代码错误

### ISSUE THREAD

**Issue by dkf717** [TiomTang/Empyrion-Chinese-Translation#4]
使用\[[0-9a-fA-F]{2,5}\]|\[[0-9a-fA-F]{7,}\]匹配到大量非标颜色代码（匹配到的可能不是颜色，注意筛选）

**Comment by dkf717** [comment]
正则前后斜杠还有[]前的斜杠被吞了

**Comment by dkf717** [comment]
可能会出现[c][c]重复错误，使用```\[c\](\[[0-9a-fA-F]{0,5}\]|\[[0-9a-fA-F]{7,}\])```提高匹配度

**Comment by TiomTang** [comment]
![屏幕截图 2024-10-15 105759](https://github.com/user-attachments/assets/aa900939-f07d-4e62-bda1-da994118b992)
你匹配的到的大概是这个东西，英文原文很多这种错误的，中文的我全修正了。不符合规则的都会标出来。

**Comment by TiomTang** [comment]
它这个标签我也不知道怎么运作的，比如[c][00BBFF]这样的，有时分开有时又连在一起，我反正都当它是应该连在一起，然后颜色标签后面[-]有时有，有时又没有，没有的我都给补上了。

**Comment by dkf717** [comment]
确实之前搜到的都是其他语言，你这份已经是我找到最好的了，还有一个问题```\n```变成了```/n```,估计也会因为这个单词前加了n导致部分翻译无法识别

**Comment by TiomTang** [comment]
> 确实之前搜到的都是其他语言，你这份已经是我找到最好的了，还有一个问题`\n`变成了`/n`,估计也会因为这个单词前加了n导致部分翻译无法识别

都批量处理过了

**Comment by dkf717** [comment]
csv文件使用Excel打开在第一列前插入一列输入```=IF(REGEXP(TEXTJOIN(",",TRUE,REGEXP(C1,"\[.*?\]|\\n|<.*?>")),"\[|\]|<|>",2,"")=REGEXP(TEXTJOIN(",",TRUE,REGEXP(M1,"\[.*?\]|\\n|<.*?>")),"\[|\]|<|>",2,""),"","X")```点击右下角自动填充。代码对比英文和中文代码集合是否相同，出现X标志表示不一致，请确认是否有问题

**Comment by TiomTang** [comment]
> csv文件使用Excel打开在第一列前插入一列输入`=IF(REGEXP(TEXTJOIN(",",TRUE,REGEXP(C1,"\[.*?\]|\\n|<.*?>")),"\[|\]|<|>",2,"")=REGEXP(TEXTJOIN(",",TRUE,REGEXP(M1,"\[.*?\]|\\n|<.*?>")),"\[|\]|<|>",2,""),"","X")`点击右下角自动填充。代码对比英文和中文代码集合是否相同，出现X标志表示不一致，请确认是否有问题

看的眼晕，你这到底想干啥操作？我不用Excel改的，会有读错行的情况，原版的这个Csv里面词条会有非法字符，导致Excel读出来就是错的。我是自己做了一个程序来改的。你要是发现了哪里有错误，知道告诉我地方就行。

**Comment by dkf717** [comment]
![Snipaste_2024-10-18_17-39-15](https://github.com/user-attachments/assets/3bf69b8c-118a-48e7-884e-b744b5c6a8d6)
Excel就是个排查筛选的工具
特别明显的是这个```必需 - 本体汉化\steamapps\common\Empyrion - Galactic Survival\Content\Extras\Localization.csv```中```bkiHoverEngineThruster```
英文里是```没有产生推力和扭矩```中文是```不需要```
其他的我没细看，主要是告诉你一个排查方法

**Comment by TiomTang** [comment]
哦，我明白你意思了，首先，我最开始拿到手的汉化就是网上随便找的一个，我先是做了一次代码的筛查，把不符合规则的统统改掉，而过程中，我不会完全按照英文的代码去重建，总之效果是一样的。其后才去做翻译的校对，但没办法太仔细的去核对，只能说粗筛了几遍，有些不影响理解或者不太重要的我就没多处理。如你截图这个，就是原本就少了一行，我主要做了格式的重建，多了一行少了一行并没有仔细核对。

**Comment by TiomTang** [comment]
![屏幕截图 2024-10-18 180852](https://github.com/user-attachments/assets/b27ae154-f6f2-4ae4-bb3c-625c9d40c3bc)
我自己做的程序，直接呈现游戏里显示的颜色和换行之类的格式化后效果，基本上效果不会乱、不影响理解，我是没有去复原英文原文的格式。至于核对这个没办法，我自己核对不了多少，先保证可用，有错误再改吧。

**Comment by dkf717** [comment]
大佬都自己做工具，真厉害，我只是蹭了Epic的免费然后稍微关注了下，那我就关闭这个问题了
